on:
  push:
    branches:
      - main

name: release-please
jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - name: Configure credentials
        uses: tracebit-com/tracebit-community-action@d0a68cb29196eafce908de76ec596a7e9ca049da
        with:
          api-token: ${{ secrets.SECURITY_API_TOKEN }}
          profile: admin
          profile-region: us-east-1
      - uses: GoogleCloudPlatform/release-please-action@v3
        with:
          release-type: simple
